### ISSUE TITLE
Add a way to force mandatory upgrades

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#137]

**Comment by themandalore** [comment]
e.g. when we update indexes.json or manualData.json
When there's a breaking change, we want them to upgrade or have to manually override

**Comment by mikeghen** [comment]
Doesn't adding new PSRs to the end of the request Ids and the `MaxPSRID` code fix this? I think shuffling the PSRs around happened once in the past and should never happen again, I got disputed when you did that and lost 1000 TRB, new PSRs should always be appended, they should never be shuffled, this would solve the issue. You just added that `MaxPSRID` function so I think that solves the problem, and then just don't shuffle PSRs ever, treat them as immutable, its not like their scarce. This only breaks if someone comes along and decides to start using one of the PSRs (like PSR 999) without informing anyone what it's for, but in that case, submitting 0 values would be appropriate.

**Comment by themandalore** [comment]
I completely agree, but for me, it's also about looking at upgrades and other things we may not foresee.  There should just be some way for us to push to the miner that they need to upgrade or override in the config file
