### ISSUE TITLE
Remove the use of global context

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#188]
Using ctx to hold global state leads to many problems as there is no way to track which comment updates the global context, should refactor it to pass data to each components to decouple from the global context. Using global context is also very difficult to make race-free

Code like this should be removed.
`context.WithValue(ctx, tellorCommon.NewTransactorContractContextKey, newTransactorInstance)`

**Comment by JGcarv** [comment]
Can we close this one?

**Comment by krasi-georgiev** [comment]
yep, not sure why it didn't close from the PR
