### ISSUE TITLE
Make Average and Safe Low gas available in rpc/contractRPC.go

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/telliot#197]
The DB currently only saves one value for gas, the Fast price. So in rpc/contractRPC.go, there is only the fast gas price available to use for submissions:
```
gasPrice := getInt(m[db.GasKey])
```
However, it would be better to have average and safe low prices available so miners could select which one to use. I looked into it but seems like this issue involves a good amount of work on the DB

**Comment by themandalore** [comment]
Add better gas estimation in general.  There should be ways to look at predicted costs (some API's have it)

**Comment by krasi-georgiev** [comment]
With the recent refactoring can add a configuration option for the GasTracker module to specify which gas to return when queried
