### ISSUE TITLE
Add prometheus metrics to allow monitoring the process and submitd valued for disputes.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#202]
Once the codebase has metrics should also update the release doc to add a reminder for adding changed metrics to the changelog.

Some examples of potentially useful metrics

total submitted transactions
total failed transactions
total cost
total profit
profit per transaction
uptime

For disputes can also add a metric for expected vs actual values and alert on these. This way miners can be notified of bad values in the oracle contract. A way to implement is -check my submitted value if it deviates too much from the other submitted values send and alert

Can probably make another survey or add to the existing one for metrics people would like to see in the miner.

Eventually, we can also build grafana dashboards for people to use to monitor all their miners.

**Comment by themandalore** [comment]
Some examples of potentially useful metrics

total submitted transactions
total failed transactions
total cost
total profit
profit per transaction
uptime

Can probably make another survey or add to the existing one for metrics people would like to see in the miner.

Eventually, we can also build grafana dashboards for people to use to monitor all their miners.

**Comment by krasi-georgiev** [comment]
@mikeghen would that be useful to you? If yes what kind of metrics would you like to see first?
