### ISSUE TITLE
AMPL Value not Available

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/telliot#229]
Sometimes the AMPL/USD price isn't available even after 24 hours

**Comment by themandalore** [comment]
help us replicate @mikeghen 

But we know that the 24hr average is still a pain and we're open for Ideas on fixing these

**Comment by mikeghen** [comment]
@themandalore, it's tricky, I first noticed the issue after removing the Kucoin endpoint in mid-October, I added it back after the AMPL price issue last week just to see how it behaved and it worked again. I'm still experimenting in development with it, but I haven't upgraded to the latest version yet, if I find anything useful, I'll post it here
