### ISSUE TITLE
Tellor Data Dashboard or API endpoint

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/telliot#231]
Create an interface for viewing the data values in the TellorMiner's local database

**Comment by krasi-georgiev** [comment]
I am also not a big fan of how the data is saved and retrieved from the DB so will deff do some improvements here. 

> viewing the data values

Can you give an example of how you imagine this? Just a simple example would help. 
Are you thinking maybe some graphql or rest API?

**Comment by mikeghen** [comment]
@krasi-georgiev I never saw your comment but I just wanted to bump this, really miners just need an easy way to see the exact values in the database, this becomes more important as we start adding more request IDs, its difficult to verify the data is correct in the database without putting some log messages, or maybe there is and I'm not aware of it. Just any easy way to see the data values in the DB is needed so it can be viewed. Even if its just a log.Info message that can be enabled in `loggingConfig.json`

**Comment by krasi-georgiev** [comment]
but why do you need to see the data? What is just add a way that a stratum server can submit solutions and the miner becomes just a submitter. So all it does is listens for solutions and as soon as there is a solution is submits it to the contract.
