### ISSUE TITLE
Replace the cli package with Kingpin.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#240]
Kong cli is the successor of kingpin It allows more flexibility and will also allow staking commands and cli flags attached to a given command and not globally

https://github.com/alecthomas/kong

Here is a good example of how to implement
https://github.com/prometheus/test-infra/blob/master/infra/infra.go

**Comment by JGcarv** [comment]
Starting on this today!

**Comment by krasi-georgiev** [comment]
Can you please add a start a simple google doc(paste link here or PM me) on how you intend to structure the commands. I want to see how it would look like and probably discuss changes.

PS. need to remember to add an entry in the changelog file as it is affecting end users.

**Comment by JGcarv** [comment]
This is what I have mapped out:
https://gist.github.com/JGcarv/d703ae9cec7b141187ba8e6e689ed518

**Comment by krasi-georgiev** [comment]
closed in https://github.com/tellor-io/telliot/pull/320
