### ISSUE TITLE
Allow using multiple staked pub/priv keys to submit a solution

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/telliot#242]
It would be great to have a way for other services to "subscribe" to the miner either through sockets or through webhooks. Things like new challenge updates and solution submissions are what's needed in other services to support mining.

**Comment by krasi-georgiev** [comment]
had a sync chat with the team and @mikeghen and we will towards allow a single miner to be able to use multiple staked pub/priv key pairs and round-robin the solution submission. This way a single miner doesn't have to stay idle during the 15min restriction rule.

Will update the title to describe the issue a bit better.
