### ISSUE TITLE
Add override for specific request ID

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#249]
use of manualData.json or similar.  
We need to allow manual override of values if there is no value in the database

**Comment by krasi-georgiev** [comment]
The main problem is that current override in `indexes.json` works on per symbol basis and not per request ID

**Comment by krasi-georgiev** [comment]
for example for the `BTC/USD` you have 2 different request IDS - redID 2 is  for the median and redID 4 one for TimeWeightedAvg so if you add an entry in the manual.json like 
```
"BTC/USD": {
        "VALUE": 111.442,
        "DATE": 1606694400
    }
```
this will override the values for both request IDs and we might want to  override just for redID 2 for example.

**Comment by themandalore** [comment]
clean up the fact that we add an override in like 3 different places
