### ISSUE TITLE
Remove the GPU mining code as noone uses it.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#267]
this should be done only after fixing the stratum pool mining in https://github.com/tellor-io/TellorMiner/issues/266.

This will unblock is to have automated building and testing for windows and osx.

**Comment by Spuddyminer** [comment]
I still do use the GPU mining code when mining on the Mainnet, but if I'm the only one using it then it's not worth keeping...Maybe we could we open this up to the community?

**Comment by krasi-georgiev** [comment]
Yep got it. Will leave this open for a while and will see what are the opinions. Will also post on discord at some point as well.

Thanks for the feedback

**Comment by Spuddyminer** [comment]
So, I don't think the GPU miner makes a difference for me after all! I just wanted to post here again because I dissented initially, but now I also think it can probably go unless others want to keep it.

**Comment by krasi-georgiev** [comment]
I am thinking to make the tool only a `submitter`. 
This is what I think will work:
send a challenge to an external `solution solver` - this can be a stratum pool or just a GPU miner
when the challenge is solved it will be sent to the `submitter`
the submitter then will handle the submission to the chain.

If someone needs to still use a gpu mining I can create a single Docker image that will include the `submitter` and the `gpu miner` inside. The gpu miner will be just the current gpu mining code extracted into an external tool

**Comment by krasi-georgiev** [comment]
here are few miners that we can probably use
https://github.com/sgminer-dev/sgminer
https://github.com/xmrig/xmrig

We just need to figure out some standard protocol to use when sending and receiving the data with the external miners
