### ISSUE TITLE
Staker Status for Dataserver is provided to all connected Miners

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/telliot#292]
When you set up a separate dataserver and specify a public/private key, the status of that public address is provided for all the miners connected to the datasever. 

https://github.com/tellor-io/telliot/blob/13ab4c229e8a8f2f5b50bd8a400e5569e994e248/cmd/telliot/main.go#L297

It looks like the disputeKey is only set for the 1 public address that the data server is using. So, other miners with different public addresses are dependant on the data server's public address being staked.

**Comment by krasi-georgiev** [comment]
Thanks for the report, can you also add steps to reproduce so we can replicate easier.

**Comment by mikeghen** [comment]
1. Make a datasever with a unstaked miner public address
2. Make a miner with a staked miner public address connected to the dataserver

Expected: miner starts up and dataserver serves it
Actual: miner never starts up because dataserver public address is unstaked
