### ISSUE TITLE
Add a check to NOT submit a solution when the miner has already submitted for the current block.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#294]
A miner can't submit more than once for an oracle mining block so more than one transaction for a given mining block causes failed transactions and  wasted gas.

It should be possible to check the contract  if the miner already submitted for the current block and only then submit.

**Comment by themandalore** [comment]
I think we do this already, but the bigger issue is that we just resubmit if waiting for it to mine.  We should update that logic...either way, I'll take a deeper look on this one this week
