### ISSUE TITLE
Remove shared Global config, move the dedicated config fields into mine or dataserver config components, and validate and use  strict parsing

### ISSUE THREAD

**Issue by JGcarv** [tellor-io/telliot#326]
After parsing the configuration json, we create a shared instance of config struct and keep it in the global state.

A better practice is to parse de config and pass each needed information to the components and function.

**Comment by krasi-georgiev** [comment]
tl-dr we need to remove https://github.com/tellor-io/telliot/blob/master/pkg/config/config.go#L223
