### ISSUE TITLE
GH action to always redeploy to google cloud on new commits to master

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#408]
At the moment we always use the master version on google cloud, but it is not automatically re-deployed when we push to master. Because of this, we catch problems with commits quite late. Instead of this we can re-deploy on every commit and catch these quickly so it would be easier to know which commit broken something.

This one seems like it will do the job
https://github.com/marketplace/actions/kubectl-google-cloud-gke-cluster

We would want to deploy from the example config which will ensure that it is always up to date.

The same GH action should also be applied to the dev branch so that we can deploy from a branch without PR reviews

**Comment by imaginebeingatcomputers** [comment]
@krasi-georgiev do you have an environment you'd like me to test this in, or would you prefer I utilize one of my own clusters?

**Comment by krasi-georgiev** [comment]
I would say use a use a trial google account it has enough free credit
