### ISSUE TITLE
Profit calculation is incorrect because the gas used varies on even and odd oracle blocks.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/telliot#426]
for slot five the gas varies
1,671,890 for some oracle blocks 
and
1,776,264 for other oracle blocks.

It seems that we need to adjust the profit calc to save the gas used in a different way.

**Comment by JGcarv** [comment]
Wait, seriously? I have no idea why that happens

**Comment by krasi-georgiev** [comment]
yep , look at the gas usage for these 2 transactions

https://etherscan.io/tx/0x938a71c9c02a4a1fd561ff7f682e3a7f66e3b8efad04c3d7487f430e39f339be
https://etherscan.io/tx/0x8e5aeca09d9eb9e0679e2d68dbb1cfe5f61b8e2b1c637819843a8bcee1133be4

It is actually quite random. some use 100-110k more gas.

Do you think this is normal or some extra variable causing this?

**Comment by krasi-georgiev** [comment]
aah could it be because the values for some data Ids have more numbers in them? like the TVL
