### ISSUE TITLE
Fellowship custom data submission rules

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#439]
Adding as a placeholder, probably multiple issues here. 
We need to be able to submit based on if:
-  there is a % change in a price
- and/or it has been a certain timeframe (e.g. 1 min)

Now the split part.  We want to be able to run this process for just one (or a handful of) datapoints.  So you would have say 2 data points running and submitting them every 10 seconds or under on a custom chain.  Then you also need to make sure that you're pulling the API at least that frequently too.

**Comment by krasi-georgiev** [comment]
This has been added as part of the telliot access submitter,
I think it is best to close for now and can open more specific issues for any further changes
