### ISSUE TITLE
Add a pause when starting

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#457]
A bunch of errors spit out while the db is syncing...just have it wait a minute for the db to sync before starting to mine

**Comment by krasi-georgiev** [comment]
I looked into it, but we will always get some errors when starting even with a pause. some Data IDs require 10m windows others are looking at 24 EOD so can't adjust the wait time for these.

I even implemented the code to add wait for the first run, but don't think we should have this extra complexity just to avoid few error logs. 

In https://github.com/tellor-io/telliot/pull/455 I have reduced the retry time to 30secs so less frequent error and added a log entry for a WARNING that on a fresh DB it is normal to see some query errors.

Closing for now but please reopen if you think we should revisit and improve it somehow.
