### ISSUE TITLE
ID 10 not reaching confidence (rinkeby)

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/telliot#475]
Telliot 5.8 is not able to achieve confidence for ID 10 with the default config. Restarted miners 2 days ago (on rinkeby) and they are still submitting the value from manual data.

**Comment by krasi-georgiev** [comment]
When manual data is provied it gives priority to that instead of using the data from the DB

**Comment by Spuddyminer** [comment]
why would this be the desirable functionality? The purpose of manualData is to provide a value before the database is ready to submit right? Either way, it's closed now as we will be changing to the new APIs I think.
