### ISSUE TITLE
Notify Miners of upgrades

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#48]
There should be a version number with each miner and then with the Tracker calls, the miner should also note if a new latest release has occurred. If it has, the system should spit out a warning message to notify Miners of an upgrade

**Comment by themandalore** [comment]
There should be a version number with each miner and then with the Tracker calls, the miner should also note if a new latest release has occurred.  If it has, the system should spit out a warning message to notify Miners of an upgrade

**Comment by krasi-georgiev** [comment]
the api to get the latest release
https://api.github.com/repos/tellor-io/telliot/releases/latest
